# Generated by Django 2.1.3 on 2018-12-04 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter a business' brand name or a user's name.", max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='e.g. 0912345678', max_length=10)),
                ('address', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('o', 'On loan'), ('a', 'Available'), ('d', 'Discarded'), ('r', 'Returned, to be cleaned')], default='r', help_text='Cup availability', max_length=1)),
                ('owner_type', models.CharField(choices=[('b', 'Business'), ('u', 'User'), ('a', 'Administration')], max_length=1)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interaction.Business')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter a business' brand name or a user's name.", max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='e.g. 0912345678', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interaction.User'),
        ),
    ]
