# Generated by Django 2.1.3 on 2018-12-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupuser',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cupuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='e.g. 0912345678', max_length=10, null=True),
        ),
    ]
