# Generated by Django 2.1.3 on 2018-12-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cup',
            name='business',
        ),
        migrations.RemoveField(
            model_name='cup',
            name='user',
        ),
        migrations.AddField(
            model_name='business',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cup',
            name='owner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cup',
            name='owner_type',
            field=models.CharField(choices=[('b', 'Business'), ('u', 'User'), ('a', 'Administration'), ('m', 'Machine')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cup',
            name='status',
            field=models.CharField(choices=[('o', 'On loan'), ('c', 'Cleaning'), ('a', 'Available'), ('n', 'Not in Circulation'), ('r', 'Returned, to be cleaned')], default='r', help_text='Cup availability', max_length=1),
        ),
    ]
