# Generated by Django 2.1.3 on 2018-12-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_auto_20181211_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='owner_type',
            field=models.CharField(choices=[('b', 'Business'), ('u', 'User'), ('a', 'Administration'), ('m', 'Machine')], default='a', max_length=1),
        ),
    ]
