# Generated by Django 2.1.3 on 2018-12-16 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_auto_20181211_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cup',
            old_name='owner_type',
            new_name='carrier_type',
        ),
        migrations.RemoveField(
            model_name='cup',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='cup',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cup',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interaction.Machine'),
        ),
        migrations.AddField(
            model_name='cupuser',
            name='is_business',
            field=models.BooleanField(default=False, verbose_name='business status'),
        ),
        migrations.AddField(
            model_name='cupuser',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='customer status'),
        ),
    ]
