# Generated by Django 2.1.3 on 2018-12-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0003_auto_20181217_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='checked_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cup',
            name='status',
            field=models.CharField(choices=[('o', 'On loan'), ('c', 'Cleaning'), ('a', 'Available'), ('n', 'Not in circulation')], default='r', help_text='Cup availability', max_length=1),
        ),
    ]
