# Generated by Django 2.1.3 on 2018-12-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0003_auto_20181211_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='status',
            field=models.CharField(choices=[('o', 'On loan'), ('c', 'Cleaning'), ('a', 'Available'), ('n', 'Not in circulation'), ('r', 'Returned, to be cleaned')], default='r', help_text='Cup availability', max_length=1),
        ),
    ]
