# Generated by Django 2.1.3 on 2018-12-25 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0007_auto_20181220_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cup',
            name='checked_out_date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='record',
            name='loaned_out_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='returned_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
