# Generated by Django 2.1.3 on 2019-01-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0009_auto_20190105_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
    ]
